'use strict';
/**
 * Category.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = {

  attributes: {
    //probably auto-generated by Mongo
    // uuid: {
    //   type: 'integer',
    //   primaryKey: true,
    //   unique: true
    // },

    name: {
      type: 'string',
      size: 50,
      defaultsTo: ''
    },

    description: {
      type: 'mediumtext',
      defaultsTo: ''
    }
  }
};
